// feed-data.jsx — seed content for the My Feed (performance) screen.
// Mara Lin's published Threads posts with realistic metrics + cumulative
// views-over-time trends. The baseline is the account's 30-day average — every
// post's badge and trend chart compare back to it.

const FEED_USER = { name: "Mara Lin", handle: "@mara.lin", initials: "ML", avatar: "assets/avatars/mara.png" };

// 30-day rolling average — the reference baseline everything compares to.
const BASELINE = {
  views: 14800,
  likes: 286,
  comments: 21,
  reposts: 12,
  posts: 18,
  deltaViews: 12, // % vs previous 30 days
};

// trend = cumulative views over the time since posting (one point per interval).
const FEED_POSTS = [
  {
    id: "f1",
    kind: "post",
    text: "Wrote 1,000 words this morning before I opened email. Cut 600 of them. The 400 that survived are the only ones that were ever going to matter.",
    time: "2d ago",
    at: "2026-05-30T09:12:00",
    tr: {
      es: "Esta mañana escribí 1.000 palabras antes de abrir el correo. Recorté 600. Las 400 que sobrevivieron son las únicas que iban a importar.",
      de: "Heute Morgen habe ich 1.000 Wörter geschrieben, bevor ich die Mails öffnete. 600 habe ich gestrichen. Die 400, die übrig blieben, sind die einzigen, auf die es je ankam.",
      fr: "Ce matin, j'ai écrit 1 000 mots avant d'ouvrir mes mails. J'en ai coupé 600. Les 400 qui ont survécu sont les seules qui allaient compter.",
      it: "Stamattina ho scritto 1.000 parole prima di aprire la posta. Ne ho tagliate 600. Le 400 sopravvissute sono le uniche che avrebbero contato.",
      pt: "Hoje de manhã escrevi 1.000 palavras antes de abrir o e-mail. Cortei 600. As 400 que sobraram são as únicas que importariam.",
      ru: "Сегодня утром я написала 1000 слов до того, как открыла почту. Вырезала 600. Оставшиеся 400 — единственные, что вообще имели значение.",
      uk: "Сьогодні вранці я написала 1000 слів, перш ніж відкрила пошту. Вирізала 600. 400, що лишилися, — єдині, що взагалі мали значення.",
    },
    span: "7 days",
    settling: false,
    autoReplies: true,
    metrics: { views: 48200, likes: 1205, comments: 84, reposts: 63 },
    peak: "Peaked Tue 2pm",
    trend: [3200, 14800, 28000, 36500, 41200, 44800, 46500, 47600, 48200],
  },
  {
    id: "f2",
    kind: "post",
    lang: "es",
    text: "El mejor comentario que recibí sobre mi escritura fueron cuatro palabras: «Puedo oírte». Tres años después, sigue siendo la única métrica en la que confío.",
    tr: {
      en: "The best feedback I ever got on my writing was four words: “I can hear you.” Three years later it's still the only metric I actually trust.",
      de: "Das beste Feedback, das ich je zu meinem Schreiben bekam, waren vier Worte: „Ich kann dich hören.“ Drei Jahre später ist es noch immer die einzige Kennzahl, der ich wirklich traue.",
      fr: "Le meilleur retour que j'aie jamais reçu sur mon écriture tenait en quatre mots : « Je t'entends. » Trois ans plus tard, c'est encore la seule mesure à laquelle je me fie vraiment.",
      it: "Il miglior commento che abbia mai ricevuto sulla mia scrittura erano quattro parole: «Ti sento». Tre anni dopo è ancora l'unica metrica di cui mi fido davvero.",
      pt: "O melhor feedback que já recebi sobre minha escrita foram quatro palavras: «Eu consigo te ouvir». Três anos depois, ainda é a única métrica em que confio de verdade.",
      ru: "Лучший отзыв о моём письме, что я получала, — четыре слова: «Я тебя слышу». Три года спустя это всё ещё единственная метрика, которой я доверяю.",
      uk: "Найкращий відгук про моє письмо, який я отримувала, — чотири слова: «Я тебе чую». Три роки потому це досі єдина метрика, якій я довіряю.",
    },
    time: "3h ago",
    at: "2026-06-01T08:40:00",
    span: "3 hours",
    settling: true,
    autoReplies: true,
    metrics: { views: 2140, likes: 71, comments: 5, reposts: 2 },
    peak: "Still climbing",
    trend: [180, 520, 980, 1450, 1860, 2140],
  },
  {
    id: "f3",
    kind: "reply",
    replyTo: { who: "@devon", text: "honestly how do you even start writing when your brain is blank" },
    text: "Start before you feel ready. I open a doc and write the worst possible first line on purpose \u2014 it kills the pressure to be good, and the real sentence usually shows up by line three.",
    time: "4d ago",
    at: "2026-05-28T16:30:00",
    tr: {
      es: "Empieza antes de sentirte listo. Abro un documento y escribo a propósito la peor primera línea posible: mata la presión de ser bueno, y la frase de verdad suele aparecer por la tercera línea.",
      de: "Fang an, bevor du dich bereit fühlst. Ich öffne ein Dokument und schreibe absichtlich die schlechtestmögliche erste Zeile — das nimmt den Druck, gut zu sein, und der echte Satz kommt meist in Zeile drei.",
      fr: "Commence avant de te sentir prêt. J'ouvre un document et j'écris exprès la pire première phrase possible : ça tue la pression de bien faire, et la vraie phrase arrive en général à la troisième ligne.",
      it: "Comincia prima di sentirti pronto. Apro un documento e scrivo apposta la peggior prima riga possibile: toglie la pressione di essere bravo, e la frase vera di solito arriva alla terza riga.",
      pt: "Comece antes de se sentir pronto. Abro um documento e escrevo de propósito a pior primeira linha possível — isso mata a pressão de ser bom, e a frase de verdade costuma aparecer na terceira linha.",
      ru: "Начинай, не дожидаясь готовности. Я открываю документ и нарочно пишу худшую первую строку — это снимает давление быть хорошим, и настоящая фраза обычно появляется к третьей строке.",
      uk: "Починай, не чекаючи готовності. Я відкриваю документ і навмисно пишу найгіршу першу строку — це знімає тиск бути добрим, і справжнє речення зазвичай з’являється до третьої строки.",
    },
    span: "7 days",
    settling: false,
    autoReplies: false,
    metrics: { views: 31800, likes: 902, comments: 47, reposts: 28 },
    peak: "Peaked Sat 9am",
    trend: [4200, 13500, 21000, 26000, 28800, 30200, 31000, 31500, 31800],
  },
  {
    id: "f4",
    kind: "post",
    text: "Stop optimizing your first sentence. Optimize the reason someone should still care by the third. Hooks fade in a scroll; substance is what compounds.",
    time: "6d ago",
    at: "2026-05-26T19:05:00",
    tr: {
      es: "Deja de optimizar tu primera frase. Optimiza la razón por la que a alguien debería seguir importándole en la tercera. Los ganchos se desvanecen en un scroll; la sustancia es lo que se acumula.",
      de: "Hör auf, deinen ersten Satz zu optimieren. Optimiere den Grund, warum es jemanden beim dritten noch interessieren sollte. Haken verblassen in einem Wisch; Substanz ist das, was sich summiert.",
      fr: "Arrête d'optimiser ta première phrase. Optimise la raison pour laquelle on devrait encore s'en soucier à la troisième. Les accroches s'effacent en un défilement ; la substance, elle, compose.",
      it: "Smetti di ottimizzare la prima frase. Ottimizza il motivo per cui a qualcuno dovrebbe ancora importare alla terza. I ganci svaniscono in uno scroll; la sostanza è ciò che si accumula.",
      pt: "Pare de otimizar sua primeira frase. Otimize o motivo pelo qual alguém ainda deveria se importar na terceira. Ganchos somem num scroll; substância é o que se acumula.",
      ru: "Перестань вылизывать первую фразу. Вылижи причину, по которой к третьей всё ещё будет не всё равно. Зацепки тают за один свайп; накапливается суть.",
      uk: "Перестань вилизувати першу фразу. Вилижи причину, з якої до третьої все ще буде не байдуже. Гачки тануть за один свайп; накопичується суть.",
    },
    span: "7 days",
    settling: false,
    autoReplies: true,
    metrics: { views: 22400, likes: 489, comments: 31, reposts: 17 },
    peak: "Peaked Thu 7pm",
    trend: [2600, 8800, 14200, 17800, 19900, 21100, 21800, 22150, 22400],
  },
  {
    id: "f5",
    kind: "post",
    text: "Underrated creative skill: being willing to be a little boring on purpose. Not every post needs a twist \u2014 some just need to be true and land on time.",
    time: "5d ago",
    at: "2026-05-27T08:15:00",
    tr: {
      es: "Habilidad creativa subestimada: estar dispuesto a ser un poco aburrido a propósito. No todo post necesita un giro. Algunos solo necesitan ser ciertos y llegar a tiempo.",
      de: "Unterschätzte kreative Fähigkeit: bereit sein, absichtlich ein bisschen langweilig zu sein. Nicht jeder Post braucht eine Wendung. Manche müssen einfach wahr sein und pünktlich landen.",
      fr: "Compétence créative sous-estimée : accepter d'être un peu ennuyeux exprès. Tout post n'a pas besoin d'une chute. Certains doivent juste être vrais et tomber au bon moment.",
      it: "Abilità creativa sottovalutata: essere disposti a risultare un po' noiosi di proposito. Non ogni post ha bisogno di un colpo di scena. Alcuni devono solo essere veri e arrivare al momento giusto.",
      pt: "Habilidade criativa subestimada: topar ser um pouco sem graça de propósito. Nem todo post precisa de uma reviravolta. Alguns só precisam ser verdadeiros e chegar na hora certa.",
      ru: "Недооценённый творческий навык — готовность быть чуть скучным нарочно. Не каждому посту нужен поворот. Некоторым достаточно быть правдой и выйти вовремя.",
      uk: "Недооцінена творча навичка — готовність бути трохи нудним навмисно. Не кожному допису потрібен поворот. Деяким досить бути правдою і вийти вчасно.",
    },
    span: "7 days",
    settling: false,
    autoReplies: false,
    metrics: { views: 15600, likes: 304, comments: 19, reposts: 11 },
    peak: "Peaked Wed 8am",
    trend: [1800, 5200, 8600, 11000, 12800, 14000, 14900, 15300, 15600],
  },
  {
    id: "f6",
    kind: "post",
    text: "A reminder I needed today: the algorithm rewards consistency, but your readers reward honesty. When they disagree, write for the second one.",
    time: "1w ago",
    at: "2026-05-25T18:20:00",
    tr: {
      es: "Un recordatorio que necesitaba hoy: el algoritmo premia la constancia, pero tus lectores premian la honestidad. Cuando estén en desacuerdo, escribe para los segundos.",
      de: "Eine Erinnerung, die ich heute brauchte: Der Algorithmus belohnt Beständigkeit, aber deine Leser belohnen Ehrlichkeit. Wenn beide uneins sind, schreib für die Leser.",
      fr: "Un rappel dont j'avais besoin aujourd'hui : l'algorithme récompense la régularité, mais tes lecteurs récompensent l'honnêteté. Quand les deux divergent, écris pour les seconds.",
      it: "Un promemoria di cui avevo bisogno oggi: l'algoritmo premia la costanza, ma i tuoi lettori premiano l'onestà. Quando sono in disaccordo, scrivi per i secondi.",
      pt: "Um lembrete de que eu precisava hoje: o algoritmo recompensa a consistência, mas seus leitores recompensam a honestidade. Quando discordarem, escreva para os segundos.",
      ru: "Напоминание, которое мне сегодня было нужно: алгоритм вознаграждает постоянство, а твои читатели — честность. Когда они расходятся, пиши для вторых.",
      uk: "Нагадування, якого мені сьогодні бракувало: алгоритм винагороджує постійність, а твої читачі — чесність. Коли вони розходяться, пиши для других.",
    },
    span: "7 days",
    settling: false,
    autoReplies: false,
    metrics: { views: 8400, likes: 142, comments: 9, reposts: 4 },
    peak: "Peaked Mon 6pm",
    trend: [1500, 3400, 5000, 6200, 7000, 7600, 8000, 8250, 8400],
  },
];

Object.assign(window, { FEED_USER, BASELINE, FEED_POSTS });
