import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Pennedly",
  description: "The terms governing your use of Pennedly.",
};

// Static legal page — a solid starting point reflecting how Pennedly actually
// works (a drafting partner, not automation). Have it reviewed by counsel
// before public launch.
const UPDATED = "May 31, 2026";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-bg text-text">
      <article className="mx-auto max-w-3xl px-6 py-16">
        <Link
          href="/"
          className="text-sm text-zinc-500 hover:text-zinc-700 dark:hover:text-zinc-300"
        >
          ← Pennedly
        </Link>
        <h1 className="mt-4 text-3xl font-semibold tracking-tight">
          Terms of Service
        </h1>
        <p className="mt-2 text-sm text-zinc-500">Last updated: {UPDATED}</p>

        <div className="mt-8 space-y-6 text-sm leading-relaxed text-text-muted [&_h2]:mt-8 [&_h2]:text-lg [&_h2]:font-semibold [&_h2]:text-text [&_a]:underline [&_a]:underline-offset-2">
          <p>
            These Terms of Service ("Terms") govern your use of{" "}
            <strong>Pennedly</strong> (the "Service"). By signing in or using
            the Service, you agree to these Terms. If you do not agree, do not
            use the Service.
          </p>

          <h2>1. Who provides the Service</h2>
          <p>
            The Service is operated under{" "}
            <strong>Fundacja Rozwoju Przedsiębiorczości "Twój StartUp"</strong>{" "}
            (KRS 0000442857, NIP 5213641211), a foundation registered in Poland.
            Contact:{" "}
            <a href="mailto:support@pennedly.com">support@pennedly.com</a>.
          </p>

          <h2>2. What Pennedly is</h2>
          <p>
            Pennedly is a <strong>drafting partner</strong> for Threads
            creators: it helps you generate posts and replies in your own voice
            and manage your presence. It is an assistant, not an autonomous
            operator — <strong>you review and decide what gets published.</strong>{" "}
            Optional automation features always run within limits you set and
            can be turned off.
          </p>

          <h2>3. Your account</h2>
          <p>
            You must provide a valid email and keep your sign-in access secure.
            You are responsible for activity under your account. You must be at
            least 16 years old.
          </p>

          <h2>4. Your content &amp; responsibility</h2>
          <p>
            You retain ownership of the content you create and publish. You are
            solely responsible for everything you publish through the Service,
            including AI-assisted drafts you approve. You confirm you have the
            right to publish it and that it complies with applicable law and the
            rules of the platforms you post to (including Threads/Meta's terms).
          </p>

          <h2>5. AI-generated drafts</h2>
          <p>
            Drafts are generated by AI and are <strong>suggestions</strong>.
            They may be inaccurate or unsuitable. Review every draft before
            publishing — once you approve and publish, it is your content and
            your responsibility.
          </p>

          <h2>6. Acceptable use</h2>
          <p>
            Do not use the Service to break the law, infringe others' rights,
            send spam, harass, or generate harmful or deceptive content; do not
            attempt to disrupt, reverse-engineer, or gain unauthorized access to
            the Service. We may suspend accounts that violate these Terms.
          </p>

          <h2>7. Third-party platforms</h2>
          <p>
            The Service connects to Threads via Meta. Your use of those
            platforms is governed by their own terms, and their availability is
            outside our control. We are not responsible for changes those
            platforms make.
          </p>

          <h2>8. Availability &amp; "as is"</h2>
          <p>
            The Service is provided "as is" and "as available". We do not
            warrant that it will be uninterrupted, error-free, or that it will
            produce any particular result (such as audience growth).
          </p>

          <h2>9. Limitation of liability</h2>
          <p>
            To the maximum extent permitted by law, we are not liable for
            indirect, incidental, or consequential damages, or for lost profits
            or data, arising from your use of the Service. Nothing in these
            Terms limits liability that cannot be limited under applicable law.
          </p>

          <h2>10. Termination</h2>
          <p>
            You may stop using the Service and request account deletion at any
            time. We may suspend or terminate access for violations of these
            Terms or to comply with the law.
          </p>

          <h2>11. Changes</h2>
          <p>
            We may update these Terms; we will revise the "Last updated" date
            and, for material changes, notify you. Continued use after changes
            means you accept them.
          </p>

          <h2>12. Governing law</h2>
          <p>
            These Terms are governed by Polish law, without prejudice to
            mandatory consumer-protection rights you may have where you live.
          </p>

          <p className="pt-4">
            See also our{" "}
            <Link href="/privacy">Privacy Policy</Link>.
          </p>
        </div>
      </article>
    </main>
  );
}
