import type { Metadata } from "next";

import { LegalLayout, type LegalDoc } from "@/components/legal/LegalLayout";

export const metadata: Metadata = {
  title: "Terms of Service — Pennedly",
  description: "The terms governing your use of Pennedly.",
  alternates: { canonical: "/terms" },
};

// Real, reviewed terms reflecting how Pennedly actually works (a drafting
// partner, not automation), rendered through the design's legal template.
// Have it reviewed by counsel before public launch.
const DOC: LegalDoc = {
  key: "terms",
  title: "Terms of Service",
  updated: "Last updated 1 June 2026",
  intro:
    'These Terms of Service ("Terms") govern your use of Pennedly (the "Service"). By signing in or using the Service, you agree to these Terms. If you do not agree, do not use the Service.',
  sections: [
    {
      id: "provider",
      h: "1. Who provides the Service",
      blocks: [
        {
          t: "p",
          text: "The Service is operated under the entity below, a foundation registered in Poland:",
        },
        { t: "operator" },
        { t: "contact", text: "Contact", email: "support@pennedly.com" },
      ],
    },
    {
      id: "what-is",
      h: "2. What Pennedly is",
      blocks: [
        {
          t: "p",
          text: "Pennedly is a drafting partner for Threads creators: it helps you generate posts and replies in your own voice and manage your presence. It is an assistant, not an autonomous operator — you review and decide what gets published. Optional automation features always run within limits you set and can be turned off.",
        },
      ],
    },
    {
      id: "account",
      h: "3. Your account",
      blocks: [
        {
          t: "p",
          text: "You must provide a valid email and keep your sign-in access secure. You are responsible for activity under your account. You must be at least 16 years old.",
        },
      ],
    },
    {
      id: "content",
      h: "4. Your content & responsibility",
      blocks: [
        {
          t: "p",
          text: "You retain ownership of the content you create and publish. You are solely responsible for everything you publish through the Service, including AI-assisted drafts you approve. You confirm you have the right to publish it and that it complies with applicable law and the rules of the platforms you post to (including Threads/Meta's terms).",
        },
      ],
    },
    {
      id: "ai-drafts",
      h: "5. AI-generated drafts",
      blocks: [
        {
          t: "p",
          text: "Drafts are generated by AI and are suggestions. They may be inaccurate or unsuitable. Review every draft before publishing — once you approve and publish, it is your content and your responsibility.",
        },
      ],
    },
    {
      id: "acceptable-use",
      h: "6. Acceptable use",
      blocks: [
        {
          t: "p",
          text: "Do not use the Service to break the law, infringe others' rights, send spam, harass, or generate harmful or deceptive content; do not attempt to disrupt, reverse-engineer, or gain unauthorized access to the Service. We may suspend accounts that violate these Terms.",
        },
      ],
    },
    {
      id: "third-party",
      h: "7. Third-party platforms",
      blocks: [
        {
          t: "p",
          text: "The Service connects to Threads via Meta. Your use of those platforms is governed by their own terms, and their availability is outside our control. We are not responsible for changes those platforms make.",
        },
      ],
    },
    {
      id: "availability",
      h: '8. Availability & "as is"',
      blocks: [
        {
          t: "p",
          text: 'The Service is provided "as is" and "as available". We do not warrant that it will be uninterrupted, error-free, or that it will produce any particular result (such as audience growth).',
        },
      ],
    },
    {
      id: "liability",
      h: "9. Limitation of liability",
      blocks: [
        {
          t: "p",
          text: "To the maximum extent permitted by law, we are not liable for indirect, incidental, or consequential damages, or for lost profits or data, arising from your use of the Service. Nothing in these Terms limits liability that cannot be limited under applicable law.",
        },
      ],
    },
    {
      id: "termination",
      h: "10. Termination",
      blocks: [
        {
          t: "p",
          text: "You may stop using the Service and request account deletion at any time. We may suspend or terminate access for violations of these Terms or to comply with the law.",
        },
      ],
    },
    {
      id: "changes",
      h: "11. Changes",
      blocks: [
        {
          t: "p",
          text: 'We may update these Terms; we will revise the "Last updated" date and, for material changes, notify you. Continued use after changes means you accept them.',
        },
      ],
    },
    {
      id: "governing-law",
      h: "12. Governing law",
      blocks: [
        {
          t: "p",
          text: "These Terms are governed by Polish law, without prejudice to mandatory consumer-protection rights you may have where you live.",
        },
      ],
    },
    {
      id: "contact",
      h: "13. Contact",
      blocks: [
        { t: "p", text: "Questions about these Terms? Reach us any time." },
        { t: "contact", email: "support@pennedly.com", text: "Pennedly — Legal" },
      ],
    },
  ],
};

export default function TermsPage() {
  return <LegalLayout doc={DOC} />;
}
